# Generated by Django 5.2 on 2025-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_item_is_approved_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to='verification_documents/'),
        ),
    ]
