# Generated by Django 5.2 on 2025-05-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_sellerprofile_identity_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='proof_of_residence',
        ),
    ]
